### ISSUE TITLE
Server Disconnected

### ISSUE THREAD

**Issue by ErroneousBosch** [jlesage/docker-handbrake#120]
Container comes up, I can see the control bar, but there is a Red X next to Handbrake and it says "Server Disconnected (1006)". The container stops running after a few minutes. Service restart on docker made no difference.

The only odd thing in my configuration is I do have the nvidia-docker libraries enabled for containers to allow for GPU transcoding in a different container.

Container log from start to container stopping itself:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing... 
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing... 
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing... 
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing... 
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing... 
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing... 
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing... 
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing... 
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing... 
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing... 
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing... 
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing... 
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing... 
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing... 
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] 95-check-optical-drive.sh: executing... 
[cont-init.d] 95-check-optical-drive.sh: looking for usable optical drives...
[cont-init.d] 95-check-optical-drive.sh: no usable optical drive found.
[cont-init.d] 95-check-optical-drive.sh: exited 0.
[cont-init.d] 95-check-qsv.sh: executing... 
[cont-init.d] 95-check-qsv.sh: Processor: Intel(R) Xeon(R) CPU X5690 @ 3.47GHz
[cont-init.d] 95-check-qsv.sh: Intel Quick Sync Video not supported: device directory /dev/dri not exposed to the container.
[cont-init.d] 95-check-qsv.sh: exited 0.
[cont-init.d] handbrake.sh: executing... 
[cont-init.d] handbrake.sh: generating machine-id...
[cont-init.d] handbrake.sh: core dump file location: |/usr/share/apport/apport %p %s %c %d %P %E
[cont-init.d] handbrake.sh: core dump file size: unlimited (blocks)
[cont-init.d] handbrake.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting certsmonitor...
[services.d] starting autovideoconverter...
[services.d] starting xvfb...
[certsmonitor] disabling service: secure connection not enabled.
[xvfb] starting...
[autovideoconverter] starting...
[autovideoconverter] Processing watch folder '/watch'...
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
[autovideoconverter] Watch folder '/watch' processing terminated.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
> Internal error:   Could not resolve keysym XF86RotationLockToggle
Errors from xkbcomp are not fatal to the X server
[services.d] starting nginx...
[services.d] starting openbox...
[nginx] starting...
[openbox] starting...
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
> Internal error:   Could not resolve keysym XF86RotationLockToggle
Errors from xkbcomp are not fatal to the X server
[services.d] starting logmonitor...
[services.d] starting x11vnc...
[logmonitor] no file to monitor: disabling service...
[services.d] starting statusmonitor...
[services.d] starting app...
[x11vnc] starting...
[statusmonitor] no file to monitor: disabling service...
18/05/2020 10:15:06 passing arg to libvncserver: -rfbport
18/05/2020 10:15:06 passing arg to libvncserver: 5900
18/05/2020 10:15:06 passing arg to libvncserver: -rfbportv6
18/05/2020 10:15:06 passing arg to libvncserver: -1
18/05/2020 10:15:06 passing arg to libvncserver: -httpportv6
18/05/2020 10:15:06 passing arg to libvncserver: -1
18/05/2020 10:15:06 passing arg to libvncserver: -desktop
18/05/2020 10:15:06 passing arg to libvncserver: HandBrake
18/05/2020 10:15:06 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 944
[app] starting HandBrake...
18/05/2020 10:15:06 Using X display :0
18/05/2020 10:15:06 rootwin: 0x43 reswin: 0x400001 dpy: 0xd2601ac0
18/05/2020 10:15:06 
18/05/2020 10:15:06 ------------------ USEFUL INFORMATION ------------------
[services.d] done.
18/05/2020 10:15:06 X DAMAGE available on display, using it for polling hints.
18/05/2020 10:15:06   To disable this behavior use: '-noxdamage'
18/05/2020 10:15:06 
18/05/2020 10:15:06   Most compositing window managers like 'compiz' or 'beryl'
18/05/2020 10:15:06   cause X DAMAGE to fail, and so you may not see any screen
18/05/2020 10:15:06   updates via VNC.  Either disable 'compiz' (recommended) or
18/05/2020 10:15:06   supply the x11vnc '-noxdamage' command line option.
18/05/2020 10:15:06 X COMPOSITE available on display, using it for window polling.
18/05/2020 10:15:06   To disable this behavior use: '-noxcomposite'
18/05/2020 10:15:06 
18/05/2020 10:15:06 Wireframing: -wireframe mode is in effect for window moves.
18/05/2020 10:15:06   If this yields undesired behavior (poor response, painting
18/05/2020 10:15:06   errors, etc) it may be disabled:
18/05/2020 10:15:06    - use '-nowf' to disable wireframing completely.
18/05/2020 10:15:06    - use '-nowcr' to disable the Copy Rectangle after the
18/05/2020 10:15:06      moved window is released in the new position.
18/05/2020 10:15:06   Also see the -help entry for tuning parameters.
18/05/2020 10:15:06   You can press 3 Alt_L's (Left "Alt" key) in a row to 
18/05/2020 10:15:06   repaint the screen, also see the -fixscreen option for
18/05/2020 10:15:06   periodic repaints.
18/05/2020 10:15:06 GrabServer control via XTEST.
18/05/2020 10:15:06 
18/05/2020 10:15:06 Scroll Detection: -scrollcopyrect mode is in effect to
18/05/2020 10:15:06   use RECORD extension to try to detect scrolling windows
18/05/2020 10:15:06   (induced by either user keystroke or mouse input).
18/05/2020 10:15:06   If this yields undesired behavior (poor response, painting
18/05/2020 10:15:06   errors, etc) it may be disabled via: '-noscr'
18/05/2020 10:15:06   Also see the -help entry for tuning parameters.
18/05/2020 10:15:06   You can press 3 Alt_L's (Left "Alt" key) in a row to 
18/05/2020 10:15:06   repaint the screen, also see the -fixscreen option for
18/05/2020 10:15:06   periodic repaints.
18/05/2020 10:15:06 
18/05/2020 10:15:06 XKEYBOARD: number of keysyms per keycode 7 is greater
18/05/2020 10:15:06   than 4 and 51 keysyms are mapped above 4.
18/05/2020 10:15:06   Automatically switching to -xkb mode.
18/05/2020 10:15:06   If this makes the key mapping worse you can
18/05/2020 10:15:06   disable it with the "-noxkb" option.
18/05/2020 10:15:06   Also, remember "-remap DEAD" for accenting characters.
18/05/2020 10:15:06 
18/05/2020 10:15:06 X FBPM extension not supported.
Xlib:  extension "DPMS" missing on display ":0".
18/05/2020 10:15:06 X display is not capable of DPMS.
18/05/2020 10:15:06 --------------------------------------------------------
18/05/2020 10:15:06 
18/05/2020 10:15:06 Default visual ID: 0x21
18/05/2020 10:15:06 Read initial data from X display into framebuffer.
18/05/2020 10:15:06 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
18/05/2020 10:15:06 
18/05/2020 10:15:06 X display :0 is 32bpp depth=24 true color
18/05/2020 10:15:06 
18/05/2020 10:15:06 Listening for VNC connections on TCP port 5900
18/05/2020 10:15:06 
18/05/2020 10:15:06 Xinerama is present and active (e.g. multi-head).
18/05/2020 10:15:06 Xinerama: number of sub-screens: 1
18/05/2020 10:15:06 Xinerama: no blackouts needed (only one sub-screen)
18/05/2020 10:15:06 
18/05/2020 10:15:06 fb read rate: 1552 MB/sec
18/05/2020 10:15:06 fast read: reset -wait  ms to: 10
18/05/2020 10:15:06 fast read: reset -defer ms to: 10
18/05/2020 10:15:06 The X server says there are 10 mouse buttons.
18/05/2020 10:15:06 screen setup finished.
18/05/2020 10:15:06 

The VNC desktop is:      5ede0feb8c92:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

GLib-GIO-Message: 10:15:06.794: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping statusmonitor...
[services.d] stopping x11vnc...
caught signal: 15
18/05/2020 10:22:44 deleted 40 tile_row polling images.
[services.d] stopping logmonitor...
[services.d] stopping openbox...
[services.d] stopping nginx...
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
> Internal error:   Could not resolve keysym XF86RotationLockToggle
Errors from xkbcomp are not fatal to the X server
[services.d] stopping xvfb...
[services.d] stopping autovideoconverter...
[services.d] stopping certsmonitor...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
```

**Comment by ErroneousBosch** [comment]
of course, immediately after I post this and test it in FF, it works there. but not in Chrome

**Comment by jlesage** [comment]
You seem to have 2 different issues. The fact that you can see the UI in FF but not in Chrome is usually an indication that clearing the browser's cache is needed.  However, this particular issue is not related to the container automatically stopping...

**Comment by ErroneousBosch** [comment]
That was my thinking and why I didn't close the issue. 
Now, once I got it going in Firefox, it did work and stay up. It is still technically running right now, so this may be a non-issue now. 

I did try a cache clear and hard reload in Chrome with no luck,  though an incognito window does work.

**Comment by ksjc** [comment]
I am having the same issues and I have tried FF, Chrome, IE, and Edge.

`,
******************************************************************************,
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?,
,
The scheme stores pixel data offscreen on the VNC viewer side for faster,
retrieval.  It should work with any VNC viewer.  Try it by running:,
,
    x11vnc -ncache 10 ...,
,
One can also add -ncache_cr for smooth 'copyrect' window motion.,
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching,
,
GLib-GIO-Message: 19:11:21.193: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.,
[services.d] stopping services,
[services.d] stopping app...,
[services.d] stopping logmonitor...,
[services.d] stopping x11vnc...,
caught signal: 15,
21/05/2020 19:11:22 deleted 40 tile_row polling images.,
[services.d] stopping statusmonitor...,
[services.d] stopping openbox...,
[services.d] stopping autovideoconverter...,
The XKEYBOARD keymap compiler (xkbcomp) reports:,
> Warning:          Unsupported high keycode 372 for name <I372> ignored,
>                   X11 cannot support keycodes above 255.,
>                   This warning only shows for the first high keycode.,
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle,
> Internal error:   Could not resolve keysym XF86RotationLockToggle,
Errors from xkbcomp are not fatal to the X server,
[services.d] stopping xvfb...,
[services.d] stopping nginx...,
[services.d] stopping certsmonitor...,
[services.d] stopping s6-fdholderd...,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] syncing disks.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 00-app-niceness.sh: executing... ,
[cont-init.d] 00-app-niceness.sh: exited 0.,
[cont-init.d] 00-app-script.sh: executing... ,
[cont-init.d] 00-app-script.sh: exited 0.,
[cont-init.d] 00-app-user-map.sh: executing... ,
[cont-init.d] 00-app-user-map.sh: exited 0.,
[cont-init.d] 00-clean-logmonitor-states.sh: executing... ,
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.,
[cont-init.d] 00-clean-tmp-dir.sh: executing... ,
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.,
[cont-init.d] 00-set-app-deps.sh: executing... ,
[cont-init.d] 00-set-app-deps.sh: exited 0.,
[cont-init.d] 00-set-home.sh: executing... ,
[cont-init.d] 00-set-home.sh: exited 0.,
[cont-init.d] 00-take-config-ownership.sh: executing... ,
[cont-init.d] 00-take-config-ownership.sh: exited 0.,
[cont-init.d] 00-xdg-runtime-dir.sh: executing... ,
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.,
[cont-init.d] 10-certs.sh: executing... ,
[cont-init.d] 10-certs.sh: exited 0.,
[cont-init.d] 10-cjk-font.sh: executing... ,
[cont-init.d] 10-cjk-font.sh: exited 0.,
[cont-init.d] 10-nginx.sh: executing... ,
[cont-init.d] 10-nginx.sh: exited 0.,
[cont-init.d] 10-vnc-password.sh: executing... ,
[cont-init.d] 10-vnc-password.sh: exited 0.,
[cont-init.d] 10-web-index.sh: executing... ,
[cont-init.d] 10-web-index.sh: exited 0.,
[cont-init.d] 95-check-optical-drive.sh: executing... ,
[cont-init.d] 95-check-optical-drive.sh: looking for usable optical drives...,
[cont-init.d] 95-check-optical-drive.sh: found optical drive /dev/sr0, but it is not usable because is not exposed to the container.,
[cont-init.d] 95-check-optical-drive.sh: no usable optical drive found.,
[cont-init.d] 95-check-optical-drive.sh: exited 0.,
[cont-init.d] 95-check-qsv.sh: executing... ,
[cont-init.d] 95-check-qsv.sh: Processor: Intel(R) Atom(TM) CPU D525 @ 1.80GHz,
[cont-init.d] 95-check-qsv.sh: Intel Quick Sync Video not supported: device directory /dev/dri not exposed to the container.,
[cont-init.d] 95-check-qsv.sh: exited 0.,
[cont-init.d] handbrake.sh: executing... ,
[cont-init.d] handbrake.sh: core dump file location: core,
[cont-init.d] handbrake.sh: core dump file size: unlimited (blocks),
[cont-init.d] handbrake.sh: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] starting s6-fdholderd...,
[services.d] starting certsmonitor...,
[services.d] starting nginx...,
[services.d] starting xvfb...,
[nginx] starting...,
[certsmonitor] disabling service: secure connection not enabled.,
[xvfb] starting...,
The XKEYBOARD keymap compiler (xkbcomp) reports:,
> Warning:          Unsupported high keycode 372 for name <I372> ignored,
>                   X11 cannot support keycodes above 255.,
>                   This warning only shows for the first high keycode.,
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle,
> Internal error:   Could not resolve keysym XF86RotationLockToggle,
Errors from xkbcomp are not fatal to the X server,`

**Comment by jlesage** [comment]
@ksjc, is the container stops itself ?  Did you try to clear the browser's cache or try in incognito mode ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
