### ISSUE TITLE
Specifying more than one custom arg

### ISSUE THREAD

**Issue by Ed2027** [jlesage/docker-handbrake#164]
Hello

I'm having problems when trying to specify more than one custom arg to AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS. Could some examples be provided? I'm trying to pass in  --audio-lang-list=eng as well as --first-audio

Thanks

**Comment by jlesage** [comment]
Normally, using something like `-e AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS="--audio-lang-list=eng --first-audio"` should work.

**Comment by Ed2027** [comment]
Thanks for comming back. It doesn't seem to be doing what I need. 

If I try  

> -e AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS=“--audio-lang-list=eng --first-audio” \)

then from the terminal window, I get 

> unknown flag: --first-audio”

I've tried splitting it over two lines e.g.

>     -e AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS=“--audio-lang-list=eng” \
>     -e AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS=“--first-audio” \

But just end up with two audio tracks baked into the video output (first one is vietnamese, second is english)

**Comment by jlesage** [comment]
It seems to work for me.  However, I see in the comment you posted that the double quotes character used is not the right one.  Make sure to type yourself the double quotes, instead of copy-pasting to make sure the correct one is used.

If you run `docker inspect <name of the container>`, you should see if the environment variable is correctly set:
```
            "Env": [
                "AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS=--audio-lang-list=eng --first-audio",
               ...
            ],
```

**Comment by jlesage** [comment]
https://github.com/jlesage/docker-handbrake#hooks
