### ISSUE TITLE
Question: Can I setup Handbrake to use RAM?

### ISSUE THREAD

**Issue by lilbumblebear** [jlesage/docker-handbrake#168]
Hi, I'm a noob with all of this, so I apologize if this is a silly question.  I noticed that on the Unmanic Library Optimizer there is an option to set the Encoding Cache Directory to RAM.  I was wondering if something like this is possible with this container too?  

Thank you!

**Comment by jlesage** [comment]
I'm not really familiar with Unmanic, but I guess the temporary folder is used to encode the video before move it back to the original location.
This concept doesn't really apply to this container: videos from a source are encoded directly to their final location in a different directory.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.

**Comment by RikudouGoku** [comment]
> Closing this issue. Please re-open if needed.

Has this feature been added?

https://docs.unmanic.app/docs/installation/unraid/#configuring-ram-as-the-cache-directory
Another example would be using it for jellyfin transcode folder.

It should work for handbrake as well I think, instead of having the file be continously updated and written over and over to when it is on the drive (especially for SSDs) it would be better for the drive health if it was using the ram instead.
