### ISSUE TITLE
UNRAID-docker "can not read or write the directory"

### ISSUE THREAD

**Issue by fuchenw** [jlesage/docker-handbrake#230]
After I deleted a shared user it didn't work, tried everything, including reinstalling. just keep tells "can not read or write the directory"

PS.
1.the output folder owner just keep being "nobody"
2.the auto convert works

Storage:set
Output Directory: set
userid:99
groupid:100

**Comment by jlesage** [comment]
Who is giving this error message and when ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.

**Comment by Kleinja** [comment]
I'm seeing an issue similar to this I wanted to mention. Thought it would be best to post here rather than create a new issue, but feel free to move it to a new issue if that is best. Currently running Latest (24.03.1)

I was playing around with my profiles and wanted to do some manual testing. For reference, the automatic video converter has been working wonderfully ever since I got this setup on my new rig. It is in docker (deployed with Portainer) running in an ubuntu LXC. I edited my config to disable the automatic video converter (which was fine). Though when trying to run a file manually from the GUI, I keep seeing the error "Invalid Destination, Destination: /output, can not read or write the directory". 

Loaded in a file manually from the /watch folder, and set the output directory to the /output folder. When pressing "add to queue" or "start" the issue pops up. Tried with multiple presets, which made no difference. 

I wouldn't think it is a permissions issue, as the auto converter uses both of those folders and has no issues writing to /output. I tried exporting the file to the /output and even the /watch folder and saw this error to both locations. 

Any things I should try to see if that gets it working? Or is there some sort of bug with the manual process that is causing this error to popup? This is the first time I am trying to run a file manually after setting everything up on my new system, but in the past, on my old system, I have ran some things this way without issues. It has been a while though, so I am sure there has been some newer versions released since then.
