### ISSUE TITLE
Handbrake 1.6 support

### ISSUE THREAD

**Issue by MrJoermungandr** [jlesage/docker-handbrake#241]
Hey really love the image so take your time with the update just wanted to kknow if theres a rough schedule for the implementation :)

**Comment by jlesage** [comment]
Hi,

I'm currently finalizing changes needed to use the new baseimage that will bring a lot of enhancements.

Once done, I will update Handrake to version 1.6.  This part can be done very quickly if everything compiles smoothly, but we never know with new major HandBrake versions...

**Comment by MrJoermungandr** [comment]
very cool thanks for the awesome work

**Comment by jlesage** [comment]
Let's keep this issue open until the new image is released.  I'm sure others will have the same question :)

**Comment by veryprogram** [comment]
You're the best for keeping this project up to date. ❤️

**Comment by khromov** [comment]
Thank you for providing all these great images! 🌞  Looking forward to using Handbrake 1.6 as it seems to resolve some issues around intel QSV that is causing the current container to crash after an x265 encode, not finishing it.

**Comment by gurkburk76** [comment]
I was hoping it would be as easy as changing 1.5.1 to 1.6.1 in the docker file and building it localy to get av1 encoding, i was wrong :) (but i think i'm reasonably close ;) ) An update would be most welcome as i'm currently ripping stuff to AV1 abd it would be a lot more convenient to have a dedicated machine to do this instead of my regular workstation :)

**Comment by lastlink** [comment]
@jlesage any reason you can't have a github action pull latest security changes and push a new docker image daily? metube has something similar.
https://github.com/alexta69/metube/blob/master/.github/workflows/update-yt-dlp.yml
it might also be possible to make handbrake an environment variable that can be passed into docker image to customize version used.

**Comment by jlesage** [comment]
New Docker image is now available, with HandBrake 1.6.1.

**Comment by jlesage** [comment]
> any reason you can't have a github action pull latest security changes and push a new docker image daily? metube has something similar.

Do you mean automatically push a new image with a new HandBrake version is available ?

**Comment by lastlink** [comment]
not just that, I think I've seen examples where new docker images are pushed if any dependencies have been updated.

https://hub.docker.com/r/zocker160/handbrake-nvenc a fork of your project lets you choose the handbrake version I think.

**Comment by jlesage** [comment]
From experience, because HandBrake is compiled from sources, having automatic images based on version changes doesn't work well.  Build can break easily.  Also, even if image would build successfully, it may not work at runtime.  So I prefer to make sure the image is tested before publishing it to everybody.

**Comment by jlesage** [comment]
> lets you choose the handbrake version I think

Currently there is no different images for each Handbrake version.  However, one can always goes back to a specific version of the image by using the prober Docker tag (so you can use an older version of HandBrake if needed).
